---
- name: start apcupsd
  systemd: 
    name: apcupsd.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: restart apcupsd
  systemd: 
    name: apcupsd.service
    state: restarted

- name: start avahi
  systemd: 
    name: avahi-daemon.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: start netatalk
  systemd: 
    name: netatalk.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: restart netatalk
  systemd: 
    name: netatalk.service
    state: restarted
    daemon_reload: yes

- name: start plex
  systemd: 
    name: plexmediaserver.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: restart plex
  systemd: 
    name: plexmediaserver.service
    state: restarted
    daemon_reload: yes

- name: start samba
  systemd: 
    name: smbd.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: restart samba
  systemd: 
    name: smbd.service
    state: restarted
    daemon_reload: yes

- name: enable srv-media
  systemd:
    name: srv-media.automount
    enabled: yes
    daemon_reload: yes

- name: start srv-media
  systemd:
    name: srv-media.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable srv-sites
  systemd:
    name: srv-sites.automount
    enabled: yes
    daemon_reload: yes

- name: start srv-sites
  systemd:
    name: srv-sites.mount
    state: started
    enabled: yes
    daemon_reload: yes
